#sensor 1:
- platform: mqtt
  state_topic: "owntracks/Petra/petras7"
  name: "Petra s7 Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"
#sensor 2
- platform: mqtt
  state_topic: "owntracks/Stefan/stefan_le_max_2"
  name: "Stefan Le Max 2 Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"
#sensor 3
- platform: mqtt
  state_topic: "owntracks/Marlon/Marlons2"
  name: "Marlon s2 Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"
#sensor 4
- platform: yr
- platform: time_date
  display_options:
    - 'time'
- platform: template
  sensors:
    alarm_clock_hour:
      value_template: '{{ states.input_number.alarm_clock_hour.state | int }}'
    alarm_clock_minute:
      value_template: '{{ states.input_number.alarm_clock_minute.state | int }}'
    alarm_clock_time:
      value_template: >-
        {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}
    alarm_clock_time_long:
      value_template: >-
        {% if states.sensor.alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}