alias: "low battery RGB lamp"
trigger:
  - platform: numeric_state
    entity_id: sensor.petra_s7_battery
    below: 5
  - platform: numeric_state
    entity_id: sensor.marlon_note3_battery
    below: 5
condition:
  - condition: state
    entity_id: group.all_devices
    state: "home"
action:
service: script.low_battery